steps:
  # Replace these build steps with your actual build steps
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/development-422509/test-image', '.']

options:
  logging: CLOUD_LOGGING_ONLY
